version: '3.8'
services:
  backend:
    image: luislanza19/scada-backend:latest
    container_name: scada-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend/app/db:/app/app/db
    restart: unless-stopped

  frontend:
    image: luislanza19/scada-frontend:latest
    container_name: scada-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
